### ISSUE TITLE
Fix data omission at end of file

### ISSUE THREAD

**Issue by Kokonico** [Kokonico/PNGstorage#1]
currently, encrypting than decrypting files tends to omit some data at the end of them.

this can be easily tested by encoding and decoding the main.py file.

**Comment by Kokonico** [comment]
UPDATE:

it turns out the whole thing is broken atm

I reverted the changes that broke it, working on a fix.

**Comment by Kokonico** [comment]
seems to happen again in latest version. reopening.

**Comment by LyubomirT** [comment]
@Kokonico Perhaps the issue isn't only with videos. I tried to convert a `.html` file once, and it had an unreadable non-utf8 symbol at the end. Maybe that's the issue with the video too?

**Comment by Kokonico** [comment]
Hmm, I think we need more testing on this issue, I changed the verification to check in a byte-per-byte basis, and the video passes, but using decode doesn't.

**Comment by Kokonico** [comment]
quick update @LyubomirT , I've figured out some data gets omitted at the end of the file, it's easy to see it with text files like the README and main.py file.

**Comment by Kokonico** [comment]
it seems like it has to do with the calculations for making images into perfect squares.

**Comment by Kokonico** [comment]
fixed via #9
